# Generated by Django 5.2.6 on 2025-09-19 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_recommendations', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsimilarity',
            name='product_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_as_product_1', to='products.product'),
        ),
        migrations.AddField(
            model_name='productsimilarity',
            name='product_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_as_product_2', to='products.product'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='context_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='context_product',
            field=models.ForeignKey(blank=True, help_text='Product that triggered this recommendation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='context_recommendations', to='products.product'),
        ),
    ]
