# Generated by Django 5.2.6 on 2025-09-19 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_recommendations', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('products', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendationfeedback',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='recommendationfeedback',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='ai_recommendations.recommendation'),
        ),
        migrations.AddField(
            model_name='recommendationfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendationitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='recommendationitem',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_recommendations.recommendation'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='products',
            field=models.ManyToManyField(through='ai_recommendations.RecommendationItem', to='products.product'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='model_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_recommendations.recommendationmodel'),
        ),
        migrations.AddField(
            model_name='trendingproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trending_data', to='products.product'),
        ),
        migrations.AddField(
            model_name='userbehavior',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='userbehavior',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userproductinteraction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interactions', to='products.product'),
        ),
        migrations.AddField(
            model_name='userproductinteraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='productsimilarity',
            index=models.Index(fields=['product_1', 'similarity_score'], name='ai_recommen_product_0273e6_idx'),
        ),
        migrations.AddIndex(
            model_name='productsimilarity',
            index=models.Index(fields=['product_2', 'similarity_score'], name='ai_recommen_product_16130d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productsimilarity',
            unique_together={('product_1', 'product_2', 'similarity_type')},
        ),
        migrations.AlterUniqueTogether(
            name='recommendationfeedback',
            unique_together={('user', 'recommendation', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='recommendationitem',
            unique_together={('recommendation', 'product')},
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['user', 'recommendation_type'], name='ai_recommen_user_id_b84193_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['session_key', 'recommendation_type'], name='ai_recommen_session_83e5f7_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['is_active', 'valid_until'], name='ai_recommen_is_acti_914e56_idx'),
        ),
        migrations.AddIndex(
            model_name='trendingproduct',
            index=models.Index(fields=['daily_score'], name='ai_recommen_daily_s_35dcbe_idx'),
        ),
        migrations.AddIndex(
            model_name='trendingproduct',
            index=models.Index(fields=['weekly_score'], name='ai_recommen_weekly__264c00_idx'),
        ),
        migrations.AddIndex(
            model_name='trendingproduct',
            index=models.Index(fields=['monthly_score'], name='ai_recommen_monthly_cc0102_idx'),
        ),
        migrations.AddIndex(
            model_name='userbehavior',
            index=models.Index(fields=['user', 'behavior_type'], name='ai_recommen_user_id_4fae29_idx'),
        ),
        migrations.AddIndex(
            model_name='userbehavior',
            index=models.Index(fields=['session_key', 'behavior_type'], name='ai_recommen_session_04b576_idx'),
        ),
        migrations.AddIndex(
            model_name='userbehavior',
            index=models.Index(fields=['created_at'], name='ai_recommen_created_541386_idx'),
        ),
        migrations.AddIndex(
            model_name='userproductinteraction',
            index=models.Index(fields=['user', 'total_score'], name='ai_recommen_user_id_678779_idx'),
        ),
        migrations.AddIndex(
            model_name='userproductinteraction',
            index=models.Index(fields=['product', 'total_score'], name='ai_recommen_product_c24ffc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userproductinteraction',
            unique_together={('user', 'product')},
        ),
    ]
